### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by paxos** [paxos/ghNotifier-issues#2]
- [x] Optional hide Dock icon
- [x] Highlight Statusbar Icon on new notifications
- [ ] Make refresh interval customizable (currently: 60 seconds)
- [ ] Improve first start experience
- [x] Loading indicator (during initial load and refresh)

**Comment by paxos** [comment]
Moved to individual issues
